# Generated by Django 5.0.4 on 2024-04-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_follows_delete_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
